jwt:
    access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
    refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}
    secret: ${JWT_SECRET}
spring:
    application:
        name: blogStudy
    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ${DB_PASSWORD}
        url: ${DB_URL}
        username: ${DB_USERNAME}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                jdbc:
                    time_zone: UTC
                format_sql: true
        show-sql: true
cookie:
    secure: ${COOKIE_SECURE:false}
cors:
    allowed-origin-patterns: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}