jwt:
    access-token-expiration: 300000
    refresh-token-expiration: 600000
    secret: ${JWT_SECRET}
spring:
    application:
        name: blogStudy
    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ${DB_PASSWORD}
        url: ${DB_URL}
        username: ${DB_USERNAME}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true
cookie:
    secure: ${COOKIE_SECURE:false}